name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: bun install && bun install yarn

      - name: Creating .npmrc
        run: |
              cat << EOF > "$HOME/.npmrc"
              //registry.npmjs.org/:_authToken=$NPM_TOKEN
              EOF

      - name: Get Title From Datamuse API
        id: datamuse
        run: |
          response=$(curl -s "https://api.datamuse.com/words?ml=animal")
          title=$(echo $response | jq -r '.[0].word') 
          echo "Title is $title"
          echo "RELEASE_TITLE=$title" >> $GITHUB_ENV

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          title: ${{ env.RELEASE_TITLE }}
          publish: bun package:release

